### ISSUE TITLE
Generated DKIM key is only 1024 bits

### ISSUE THREAD

**Issue by Synchro** [wesley974/mailserver#1]
The DKIM keys are generated [in the `install_system.sh` script](https://github.com/wesley974/mailserver/blob/master/install/install_system.sh#L79). 1024-bit DKIM keys have been shown to be insecure; Google ignores keys below 2048 bits, so this should be increased to at least that much, if not 3072 or 4096.

**Comment by wesley974** [comment]
I don't think that it is necessary.

1/ Some domain provider doesn't support key greater than 1024
2/ It is clairely announced here at Google : https://support.google.com/a/answer/174126?hl=en
and here : https://support.google.com/a/answer/174124?hl=en
"If your registrar doesn't support 2048-bit keys, change the key length from 2048 to 1024."
"For enhanced security, you can now generate a 2048-bit domain key instead of a 1024-bit domain key. We recommend that you generate the stronger 2048-bit key if your registrars support the longer key length. If you have a previously-generated 1024-bit domain key, it will not be affected by this change."

**Comment by Synchro** [comment]
2048-bit DKIM signatures are extremely common (google and Yahoo have used them since 2013), and the DNS system has supported long enough records for over 30 years, I think it's a bad idea to default to low-quality settings. If you're sufficiently competent to run your own mail server, you won't be using a bad DNS provider, especially since by definition this will only affect new installations, which should not be encouraged to use obsolete settings or use an incompetent DNS host. That Google support page recommends using to 2048-bit keys, and only reverting to 1024-bit if you have legacy compatibility problems, so why assume there's going to be a problem? Other similar projects have also [done this](https://github.com/mail-in-a-box/mailinabox/commit/1367816b04fbded659b7463c51173477add00f9f), or recommend you use 2048 bits [in docs](https://github.com/linode/docs/blob/691561b854c22265d4155cc7a621a12b40ed002c/docs/email/postfix/configure-spf-and-dkim-in-postfix-on-debian-8.md).

**Comment by hkparker** [comment]
PR #3 opened
